# Generated by Django 2.0 on 2019-07-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='last', max_length=255),
        ),
    ]
