# Generated by Django 2.0 on 2019-07-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='postedfor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profilemessages', to='myapp.User'),
            preserve_default=False,
        ),
    ]
