# Generated by Django 2.0 on 2019-07-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message_postedfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='postedfor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='myapp.User'),
        ),
    ]
