# Generated by Django 2.0 on 2019-07-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_message_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replymessage', to='myapp.User')),
                ('likes', models.ManyToManyField(related_name='replylikes', to='myapp.User')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagepost', to='myapp.Message')),
                ('replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.Message')),
            ],
        ),
    ]
